sonar.projectKey=devcalc-api
sonar.projectName=Meu project devcalc api

sonar.sources=src/main/java
sonar.java.binaries=target/classes

# Caminho para os testes
sonar.tests=src/test/java
sonar.java.test.binaries=target/test-classes

# Codificação do código-fonte
sonar.sourceEncoding=UTF-8

# Exclusões (opcional)
sonar.exclusions=**/generated/**,**/build/**
