name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'

jobs:
  checkout:
    name: Checkout c贸digo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c贸digo
        uses: actions/checkout@v3

  build:
    name: Build do projeto
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout do c贸digo
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean install
  test:
    name: Executar testes
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do c贸digo
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Executar testes com Maven
        run: mvn test
