name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml

  package:
    name: Gerar pacote .jar
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Gerar .jar com Maven
        run: mvn package -DskipTests

  deploy:
    name: Deploy fictício
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Exibir mensagem de deploy
        run: echo "Deploy realizado com sucesso"
